version: 1.0.{build}
os: Visual Studio 2019 Preview
skip_tags: true
configuration: Debug
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
  - dotnet build src -c Release
test_script:
  - dotnet test src
on_success:
- ps: Invoke-RestMethod https://raw.githubusercontent.com/DraxCodes/Azure-Test/master/Veyorhook.ps1 -o VeyorHook.ps1
- ps: ./VeyorHook.ps1 success $env:WEBHOOK_URL
on_failure:
- ps: Invoke-RestMethod https://raw.githubusercontent.com/DraxCodes/Azure-Test/master/Veyorhook.ps1 -o VeyorHook.ps1
- ps: ./VeyorHook.ps1 failure $env:WEBHOOK_URL